version: '3'

services:
  postdb:
    container_name: 'gostack_desafio09_tests'
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: gostack_desafio09_tests
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123456'
